version: '3'
services:
  web:
    image: flaskdb
    build: flask
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  mysqldb:
    image: mysql:latest
    ports:
      - '3316:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
volumes:
  mysql:
    driver: local
  mysql_config:
    driver: local
    